version: '3'

# FOR UNIT TESTING PURPOSES
services:
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sekr3t
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: plsdoit

  app:
    build: ./webapp
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
      MYSQL_DB: test_plsdoit
      APP_TEST: doit # This triggers pytest inside the container
