version: '3'

services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sekr3t
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret

  featy:
    build: ./webapp
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
      MYSQL_DB: pleasedoit
