version: '3'

services:
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sekr3t
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret

  app:
    build: ./webapp
    depends_on:
      - db
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
      MYSQL_DB: plsdoit
